# Generated by Django 4.2.20 on 2025-03-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_coupon_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.FloatField(help_text='Réduction en % (ex: 10 pour 10%)'),
        ),
    ]
