# Generated by Django 4.2.20 on 2025-03-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address_order_city_order_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Paiement à la livraison'), ('momo', 'Mobile Money'), ('card', 'Carte bancaire')], default='cod', max_length=20),
        ),
    ]
