# Generated by Django 4.2.20 on 2025-03-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_paid_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Paiement à la livraison'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Mobile Money'), ('card', 'Carte bancaire')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('annulee', 'Annulée'), ('livree', 'Livrée')], default='en_attente', max_length=20),
        ),
    ]
